# Generated by Django 6.0.2 on 2026-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='graph_namespace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
