# Generated by Django 6.0.2 on 2026-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_document_graph_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='graph_namespace',
        ),
        migrations.AlterField(
            model_name='document',
            name='llm_used',
            field=models.CharField(choices=[('llama3', 'Llama 3'), ('mistral', 'Mistral'), ('gpt4', 'GPT-4')], max_length=100),
        ),
    ]
