# Generated by Django 6.0.2 on 2026-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0003_remove_document_graph_namespace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='graph_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='llm_used',
            field=models.CharField(choices=[('', 'Select LLM'), ('llama3', 'Llama 3'), ('mistral', 'Mistral'), ('gpt4', 'GPT-4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=50),
        ),
    ]
