# Generated by Django 6.0.2 on 2026-03-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_document_error_message_document_graph_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='document_manager.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
