# Generated by Django 6.0.2 on 2026-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0006_qasession_qamessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamessage',
            name='question_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
