# Generated by Django 6.0.2 on 2026-04-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0007_qamessage_question_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamessage',
            name='estimated_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
