# Generated by Django 6.0.2 on 2026-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0008_qamessage_estimated_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qamessage',
            name='estimated_tokens',
        ),
        migrations.AddField(
            model_name='document',
            name='estimated_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
