# Generated by Django 6.0.2 on 2026-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0009_remove_qamessage_estimated_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='estimated_tokens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
